remote_theme: daviddarnes/alembic@main

plugins:
- jekyll-remote-theme
 
title: Football_Jersey_Recognizer
description: An image classification API that classifies 20 different types of Club Jerseys belong to Europe's top 20 football clubs.

author:
   name: Tanvir Raihan Khan

